version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
#      - npm install -g @angular/cli
  build:
    commands:
      - npm run build:$ENVIRONMENT
      - aws s3 sync dist/yaml2properties $S3_BUCKET --delete
#artifacts:
#  files:
#    - '**/*'
#  base-directory: 'dist*'
#  discard-paths: yes
